import Nav from '@/components/Nav/Nav'
import Providers from '@/lib/utils/Providers/Provider.client'
import { AppRoutes } from '@/lib/utils/constants/AppRoutes'
import GithubSvg from '@/public/github.svg'
import NextSvg from '@/public/next.svg'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import { authOptions } from './api/auth/[...nextauth]/route'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App with Next.js and Prisma',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-primary text-black min-h-screen font-medium flex flex-col`}
      >
        {/* HEADER */}
        <header className='flex justify-between items-center p-4'>
          <h1 className='text-2xl text-center uppercase text-black font-semibold'>
            <Link href={AppRoutes.Home} className='flex items-center gap-2'>
              <Image src={NextSvg} width={80} alt='Next' />
              Todos
            </Link>
          </h1>
          <Nav session={session} />
        </header>

        {/* MAIN CONTENT */}
        <main className='flex-1 flex flex-col items-center px-4 overflow-auto'>
          <Providers>{children}</Providers>
        </main>

        {/* FOOTER */}
        <footer className='w-full p-4 border-t border-gray-200 mt-auto'>
          <div className='flex justify-center items-center gap-4'>
            <Link 
              href='#' 
              target='_blank'
              rel='noopener noreferrer'
              className='flex items-center gap-2 hover:opacity-80 transition-opacity'
            >
              <Image src={GithubSvg} width={24} height={24} alt='GitHub' />
              <span>Faizan</span>
            </Link>
            <p className='text-sm text-gray-600'>
              © {new Date().getFullYear()} Todo App
            </p>
          </div>
        </footer>
      </body>
    </html>
  )
}